In [3]:
import asyncio
from googletrans import Translator
import pandas as pd
import os 


async def translate(text):
    async with Translator() as translator:
        result = await translator.translate(
            text,
            "ru", 
            "en"
        )
        return result

In [4]:
d = "../iso18245/data"
csv_list = [os.path.join(d, x)for x in os.listdir(d) if x.endswith("_translated.csv")]
csv_list

['../iso18245/data/private_ranges_translated.csv',
 '../iso18245/data/stripe_list_translated.csv',
 '../iso18245/data/iso18245_official_list_translated.csv',
 '../iso18245/data/alipay_list_translated.csv',
 '../iso18245/data/usda_list_translated.csv',
 '../iso18245/data/iso18245_ranges_translated.csv',
 '../iso18245/data/visa_list_translated.csv',
 '../iso18245/data/amex_list_translated.csv',
 '../iso18245/data/mastercard_list_translated.csv']

In [30]:

async def process_tasks(tasks):
    results =  await asyncio.gather(*tasks)
    return [
        x.text
        for x in results
    ]



async def translate_csv(file):
    df = pd.read_csv(file)
    df["DESCRIPTION_RU"] = await process_tasks([translate(x) for x in df["DESCRIPTION"]])
    return df


df = await translate_csv(csv_list[0])

In [31]:
df

,Unnamed: 0,MCC START,MCC END,DESCRIPTION,DESCRIPTION_UZ,DESCRIPTION_RU
0,0,3000,3350,Airlines,Aviakompaniyalar,Авиакомпании
1,1,3351,3500,Car rental,Avtomobil ijarasi,Прокат автомобиля
2,2,3501,3999,Lodging,Turar joy,Проживание

In [33]:

exceptions = []

for file in csv_list:
    try:
        print("Processing file: ", file)
        df = await translate_csv(file)
        df.to_csv(
            file
        )
    except Exception as e:
        exceptions.append(file)
exceptions

Processing file:  ../iso18245/data/private_ranges_translated.csv
Processing file:  ../iso18245/data/stripe_list_translated.csv
Processing file:  ../iso18245/data/iso18245_official_list_translated.csv
Processing file:  ../iso18245/data/alipay_list_translated.csv
Processing file:  ../iso18245/data/usda_list_translated.csv
Processing file:  ../iso18245/data/iso18245_ranges_translated.csv
Processing file:  ../iso18245/data/visa_list_translated.csv
Processing file:  ../iso18245/data/amex_list_translated.csv
Processing file:  ../iso18245/data/mastercard_list_translated.csv

[]

In [34]:
exceptions

[]

In [8]:
df

,Unnamed: 0.1,Unnamed: 0,MCC,DESCRIPTION,MASTERCARD_ABBREVIATED_AIRLINE_NAME,DESCRIPTION_UZ,DESCRIPTION_RU
0,0,0,742,Veterinary Services,NaN,Veterinariya xizmatlari,Ветеринарные услуги
1,1,1,763,Agricultural Cooperatives,NaN,Qishloq xo'jaligi kooperativlari,Сельскохозяйственные кооперативы
2,2,2,780,Horticultural and Landscaping Services,NaN,Bog'dorchilik va obodonlashtirish xizmatlari,Садоводные и ландшафтные услуги
3,3,3,1520,"General Contractors, residential and commercial",NaN,"Umumiy pudratchilar, turar-joy va tijorat","Генеральные подрядчики, жилые и коммерческие"
4,4,4,1711,"Air Conditioning, Heating, and Plumbing Contra...",NaN,"Konditsionerlik, isitish va sanitariya pudratc...","Подрядчики кондиционирования воздуха, отоплени..."
...,...,...,...,...,...,...,...
870,870,870,9311,Tax Payments,NaN,Soliq to'lovlari,Налоговые платежи
871,871,871,9399,Government Services: not elsewhere classified,NaN,Davlat xizmatlari: boshqa joyda tasniflangan emas,Государственные услуги: не в других местах кла...
872,872,872,9402,Postal Services: Government Only,NaN,Pochta xizmatlari: faqat hukumat,Почтовые услуги: только правительство
873,873,873,9405,Intra-Government Purchases: Government Only,NaN,Hukumat ichidagi xaridlar: faqat hukumat,Внутренние покупки: только правительство
874,874,874,9406,"Government-owned Lottery (global, excluding U....",NaN,"Hukumatning egasi lotereyasi (global, AQSh min...","Государственная лотерея (глобальная, за исключ..."